[project]
name = "fork-spider"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.ecosystem-controller]
path = "contracts/ecosystem-controller.clar"
depends_on = []

[contracts.trade-nexus]
path = "contracts/trade-nexus.clar"
depends_on = []

[contracts.trust-matrix]
path = "contracts/trust-matrix.clar"
depends_on = []

[contracts.license-ledger]
path = "contracts/license-ledger.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
